acme_news_list:
  path: /news.{_format}
  defaults:
    _controller: AcmeNewsBundle:View:list
    _format: html
  requirements:
    _format: html|xml

acme_news_full_news:
  path: /news/{newsId}
  defaults:
    _controller: AcmeNewsBundle:View:fullNews
  requirements:
    newsId: '\d+'

acme_news_root:
  path: /
  defaults:
    _controller: FrameworkBundle:Redirect:redirect
    route: acme_news_list
    permanent: true