services:

    acme_news_manager:
        class: Acme\NewsBundle\Service\AcmeNewsManager
        factory: [ 'Acme\NewsBundle\Factory\AcmeNewsManagerFactory', createNewsManager ]
        arguments:
          - "@=service('doctrine').getRepository('AcmeNewsBundle:News')"
          - "%acme_news.memcached.enabled%"
          - "@=container.has(parameter('acme_news.memcached.service_name')) ? service(parameter('acme_news.memcached.service_name')) : null"
