acme_news_list:
  path: /news.{_format}
  defaults:
    _controller: AcmeNewsBundle:View:list
    _format: html
  requirements:
    _format: html|xml

acme_full_news:
  path: /news/{pageId}
  defaults:
    _controller: AcmeNewsBundle:View:fullNews
  requirements:
    pageId: '\d+'

root:
  path: /
  defaults:
    _controller: FrameworkBundle:Redirect:redirect
    path: /news
    permanent: true